# Generated by Django 3.0.5 on 2020-05-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200515_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image_p',
            field=models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='Картинка'),
        ),
    ]
