# Generated by Django 3.0.5 on 2020-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_articles_image_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image_p',
            field=models.ImageField(blank=True, null=True, upload_to='media/articles', verbose_name='Картинка'),
        ),
    ]
