# Generated by Django 3.0.5 on 2020-05-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
