# Generated by Django 3.0.5 on 2020-05-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars', verbose_name='Аватар'),
        ),
    ]
