# Generated by Django 3.0.5 on 2020-05-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200529_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/articles', verbose_name='Аватар'),
        ),
    ]
