# Generated by Django 3.0.5 on 2020-05-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200529_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_avatar',
            field=models.ImageField(blank=True, default='media/avatar/default_img.png', null=True, upload_to='media/avatar'),
        ),
    ]
