# Generated by Django 3.0.5 on 2020-06-14 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20200614_1219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
