# Generated by Django 3.0.5 on 2020-06-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_profile_verified_token_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified_token_key',
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_token',
            field=models.CharField(default='CKWDHLVBAC', max_length=10),
        ),
    ]
