# Generated by Django 3.0.5 on 2020-06-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20200622_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified_token',
            field=models.CharField(default='CCGSFWPUEY', max_length=10),
        ),
    ]
