# Generated by Django 3.1 on 2020-09-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_auto_20200622_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified_token',
            field=models.TextField(default='2020-09-04 12:22:13.369991<django.db.models.query_utils.DeferredAttribute object at 0x040A6058><django.db.models.query_utils.DeferredAttribute object at 0x040A6148>'),
        ),
    ]
