# Generated by Django 3.1 on 2020-09-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_auto_20200904_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified_token',
            field=models.TextField(default='2020-09-04 12:23:05.513571<django.db.models.query_utils.DeferredAttribute object at 0x04416058><django.db.models.query_utils.DeferredAttribute object at 0x04416148>'),
        ),
    ]
