# Generated by Django 3.1 on 2020-09-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_auto_20200904_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verified_token',
            field=models.TextField(default=None),
        ),
    ]
